// <auto-generated />
namespace MyPassionProjectW2024n01605783.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Blog_Workout_collabs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blog_Workout_collabs));
        
        string IMigrationMetadata.Id
        {
            get { return "202404031528117_Blog_Workout_collabs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
